Docs/backlog admin
UnBArqDsw2022-2/2022.2-CopoCheio pull request #39
Opened 2023-01-03 14:46 UTC by PhRezende-eng

- This Pull Request is beeing onpened, in order of to add a new product backlog for admin user  

## Types of changes

What types of changes does your code introduce to 2022.2-CopoCheio?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ x] Documentation Update (if none of the other choices apply)

## Checklist

- [x ] I have read the CONTRIBUTING.md doc.
- [ x] I have added necessary documentation (if appropriate).
- [ ]x Any dependent changes have been merged and published in downstream modules.

2023-01-03 17:21 UTC, Sabanai104 requested changes
Boaa man, só dá um visu no que eu comentei pfvv

2023-01-03 17:21 UTC, Sabanai104 commented on docs/Modelagem/2.1.3.1.BacklogDoProduto.md
> +    <td>US03 - Eu, como usuário administrador, gostaria de alterar dados da minha conta, para que possa deixar minhas informações atualizadas</td>
Não temos isso na pagina de admin

2023-01-03 17:21 UTC, Sabanai104 commented on docs/Modelagem/2.1.3.1.BacklogDoProduto.md
> +    <td>US04 - Eu, como usuário administrador, gostaria de deletar minha conta, para que possa me desvincular da plataforma</td>
Não temos isso no admin

2023-01-03 17:21 UTC, Sabanai104 commented on docs/Modelagem/2.1.3.1.BacklogDoProduto.md
> +    <td>US15 - Eu, como administrador, gostaria de deletar comentários, para que possa tirar de site comentários que fogem do termo de serviço</td>
Teremos comentarios na aplicação?

2023-01-03 17:21 UTC, Sabanai104 commented on docs/Modelagem/2.1.3.1.BacklogDoProduto.md
> +    <td>US17 - Eu, como administrador, desejo editar as informações de bebidas cadastradas</td>
Já existe uma US para editar bebidas cadastradas, sendo ela: US11. Não está repetida essa US?

2023-01-03 17:42 UTC, Sabanai104 requested changes

2023-01-03 17:42 UTC, Sabanai104 commented on docs/Modelagem/2.1.3.1.BacklogDoProduto.md
> +    <td>US01 - Eu, como usuário administrador, gostaria de me cadastrar e enviar solicitação de confirmação de cadasto, para que eu possa gerenciar a aplicação de receitas</td>
Vamos cadastrar o usuário admin pelo banco msm, no caso os admins seria o proprio time de desenvolvimento

2023-01-03 17:42 UTC, Sabanai104 commented on docs/Modelagem/2.1.3.1.BacklogDoProduto.md
> +    <td>US02 - Eu, como usuário administrador, gostaria de visualizar minha conta, para que posso consultar minhas informações</td>
Não temos nada disso no de admin

2023-01-03 17:42 UTC, Sabanai104 commented on docs/Modelagem/2.1.3.1.BacklogDoProduto.md
> +    <td>US04 - Eu, como usuário administrador, gostaria de deletar minha conta, para que possa me desvincular da plataforma</td>
Resumindo não teremos nada do F01 dentro para o admin

2023-01-03 18:12 UTC, Sabanai104 requested changes

2023-01-03 18:12 UTC, Sabanai104 commented on docs/Modelagem/2.1.3.1.BacklogDoProduto.md
> +    <td>US08 - Eu, como usuário administrador, gostaria de buscar alguma bebida por categoria, para que eu possa facilitar minha consulta por reeceita</td>
Ta duplicada

2023-01-03 18:12 UTC, Sabanai104 commented on docs/Modelagem/2.1.3.1.BacklogDoProduto.md
> +    <td>US09 - Eu, como usuário administrador, gostaria de buscar alguma bebida por categoria, para que eu possa facilitar minha consulta por reeceita</td>
Ta duplicada

2023-01-04 00:34 UTC, PhRezende-eng commented on docs/Modelagem/2.1.3.1.BacklogDoProduto.md
> +    <td>US15 - Eu, como administrador, gostaria de deletar comentários, para que possa tirar de site comentários que fogem do termo de serviço</td>
Sim

2023-01-04 00:42 UTC, PhRezende-eng commented on docs/Modelagem/2.1.3.1.BacklogDoProduto.md
> +    <td>US01 - Eu, como usuário administrador, gostaria de me cadastrar e enviar solicitação de confirmação de cadasto, para que eu possa gerenciar a aplicação de receitas</td>
ok

2023-01-05 19:53 UTC, Sabanai104 requested changes

2023-01-05 19:53 UTC, Sabanai104 commented on docs/Modelagem/2.1.3.1.BacklogDoProduto.md
> +    <td>US03 - Eu, como usuário administrador, gostaria de autenticar com login e senha, para que eu possa acessar minha conta</td>
Unica pergunta pra eu aprovar, não tem q renumerar isso aqui? Ta começando com US03

2023-01-05 20:14 UTC, Sabanai104 approved these changes

2023-01-05 20:14 UTC, merged