feature(front-admin): arrange copo cheio`s admin application
UnBArqDsw2022-2/2022.2-CopoCheio pull request #40
Opened 2023-01-04 03:08 UTC by Sabanai104

Define patterns and themes to front-admin;
Create button, icons and text atoms with their respectives tests;
Update Read-me;
Structure folders;
Add global styles.

## Types of changes

What types of changes does your code introduce to <repo_name>?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [X] I have read the CONTRIBUTING.md doc.
- [X] I have added necessary documentation (if appropriate).
- [X] Any dependent changes have been merged and published in downstream modules.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2023-01-04 04:06 UTC, ciro-c requested changes

2023-01-04 04:06 UTC, ciro-c commented on front-admin/src/services/api.ts
> +  baseURL: 'http://localhost:5000'
Alterar para pegar a url do .env

2023-01-04 04:06 UTC, ciro-c commented on front-admin/README.md
> +Em seguida rode o comando do docker:
Se for usar o comando docker não precisa rodar npm install. O docker ja faz isso

2023-01-05 01:10 UTC, PhRezende-eng commented on front-admin/src/services/api.ts
> +  baseURL: 'http://localhost:5000'
Feito

2023-01-05 02:52 UTC, PhRezende-eng approved these changes

2023-01-05 02:53 UTC, PhRezende-eng approved these changes

2023-01-05 02:54 UTC, PhRezende-eng approved these changes

2023-01-05 02:56 UTC, PhRezende-eng approved these changes

2023-01-05 02:56 UTC, PhRezende-eng approved these changes

2023-01-05 02:58 UTC, ciro-c approved these changes

2023-01-05 02:58 UTC, merged